### ISSUE TITLE
Yocto Integration and GPIO driver

### ISSUE THREAD

**Issue by KhyatiSatta** [KhyatiSatta/final-project-KhyatiSatta#10]
DoD:
- [x] Add GStreamer and OPENCV packages to the YOCTO image
- [x] Build OpenCV application on to the YOCTO image.
- [x] Build Camera driver application on to the YOCTO image.
- [x] Develop GPIO driver to control LED.
- [x] Verify GPIO driver on target.

Blockers:
No blockers

**Comment by MaanasMDK** [comment]
Successfully added OpenCV support to Yocto build image.
Commit Link : https://github.com/cu-ecen-aeld/final-project-MaanasMDK/commit/5e791a4171f3131a8db644c39c72b9615b6f61f1


![Image](https://user-images.githubusercontent.com/89494511/233870288-eb8307bc-2754-4694-aefc-8f37e15f7970.jpg)

**Comment by MaanasMDK** [comment]
Successfully added Gstreamer support to Yocto build image.
Commit Link : https://github.com/cu-ecen-aeld/final-project-MaanasMDK/commit/bbccb3831e5e9a3ca364f243faf98f1f34bd4141



![Image](https://user-images.githubusercontent.com/89494511/233870239-ad80637f-ce48-4243-8d41-387c9735eca3.jpg)

**Comment by MaanasMDK** [comment]
Successfully added Camera driver and OpenCV application onto the yocto image.
Commit Link : https://github.com/cu-ecen-aeld/final-project-MaanasMDK/commit/a2d63090fe025013ea8fd26ddffe650afe052bc9



![Image](https://user-images.githubusercontent.com/89494511/233870277-0694394b-b9ca-4bd2-bcec-39dd2c84e2c9.jpg)

**Comment by MaanasMDK** [comment]
Successfully developed and tested GPIO driver for Raspberry PI.
Yocto Commit Link : https://github.com/cu-ecen-aeld/final-project-MaanasMDK/commit/a2d63090fe025013ea8fd26ddffe650afe052bc9
Source Commit Link : https://github.com/cu-ecen-aeld/final-project-KhyatiSatta/commit/89b8259f7abab17514b17a331769e63a1a8c13bd
Final source code link : https://github.com/cu-ecen-aeld/final-project-KhyatiSatta/commit/af08560aae357d7b52c8c622f6988ec00b6b7a05


https://user-images.githubusercontent.com/89494511/233870111-21949a7f-5a42-407c-865c-562988379d5b.MOV
