### ISSUE TITLE
OpenCV application code

### ISSUE THREAD

**Issue by KhyatiSatta** [KhyatiSatta/final-project-KhyatiSatta#6]
DoD:

- [x] Install OpenCV on the Raspbian OS
- [x] Develop the motion-detection algorithm using OpenCV
- [x] Adding features to capture from camera
- [x] Adding features to capture from a file in directory

Blockers:
No blockers

**Comment by nihalthirunakarasu** [comment]
The test code to check input from camera and display on a window can be found in the commit below:
[Commit1](https://github.com/cu-ecen-aeld/final-project-nihalthirunakarasu/commit/bb8a93e1565f2d3128962a3c2e77586abdd1b89e)


The application code to grab frames and detect any motion is added in the commit below:
[Commit2](https://github.com/cu-ecen-aeld/final-project-nihalthirunakarasu/commit/16998dcc54f64164176dd29879d40f38418e2022)

A screenshot of the algorithm developed so far is shown below:
![Image](https://user-images.githubusercontent.com/25259961/232352799-93a462b5-6246-4847-bbb0-48e11fa21e15.png)
