### ISSUE TITLE
Client driver and MQTT

### ISSUE THREAD

**Issue by KhyatiSatta** [KhyatiSatta/final-project-KhyatiSatta#9]
DoD:
- [x] Enable cross compiling for the application code developed in Sprint 1
- [x] Integrate the OpenCV code into Yocto Image
- [x] Implement the socket code for the client side
- [x] Verify sending and receiving data between the server and client Raspberry Pi (on RaspbianOS or YOCTO)

Carry forward to next sprint:
- [ ] Install all required packages for MQTT on RaspbianOS

Blockers:
No blockers

**Comment by nihalthirunakarasu** [comment]
Cross compile and integration of the application code onto yocto:
https://github.com/cu-ecen-aeld/final-project-nihalthirunakarasu/commit/0491e4cd5b5611e63e3c1deed3d9dfe895c93e59



![Image](https://user-images.githubusercontent.com/25259961/233885301-3a208da9-cc27-40ca-bd1d-7388da30608e.png)

Verified sending image from server end and receiving on the client end:
https://github.com/cu-ecen-aeld/final-project-nihalthirunakarasu/commit/41f482a887f92acb6ee248f969af900fe18dc736


The server folder is empty and does not contain any .ppm file
![Image](https://user-images.githubusercontent.com/25259961/233886994-3ecd215c-0d33-471e-babc-d8ea478b9ab3.png)

The server folder contains output.ppm file and is the same yellow image as present in the client side


![Image](https://user-images.githubusercontent.com/25259961/233888770-d145df3a-c643-4320-8239-717995871755.png)
